[build]
rustflags = ["--cfg", "tokio_unstable", "-C", "target-feature=-crt-static"]

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"
rustflags = ["--cfg", "tokio_unstable", "-C", "target-feature=-crt-static"]

[target.x86_64-unknown-linux-musl]
rustflags = ["--cfg", "tokio_unstable", "-C", "target-feature=-crt-static"]
